export const ON_EMAIL_CHANGED = "ON_EMAIL_CHANGED";
export const ON_PASSWORD_CHANGED = "ON_PASSWORD_CHANGED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const ON_TAP_BUTTON = "ON_TAP_BUTTON";
export const EMPLOYEE_UPDATE = "EMPLOYEE_UPDATE";